if(NOT DEFINED PSLOG_ROOT)
    message(FATAL_ERROR "PSLOG_ROOT is required")
endif()

foreach(public_header IN ITEMS include/pslog.h include/pslog_lua.h)
    set(header_path "${PSLOG_ROOT}/${public_header}")
    file(STRINGS "${header_path}" header_lines)
    set(documentation_ready FALSE)
    set(in_documentation FALSE)
    set(line_number 0)
    foreach(header_line IN LISTS header_lines)
        math(EXPR line_number "${line_number} + 1")
        if(header_line MATCHES "/\\*\\*")
            set(in_documentation TRUE)
        endif()
        if(in_documentation AND header_line MATCHES "\\*/")
            set(in_documentation FALSE)
            set(documentation_ready TRUE)
            continue()
        endif()
        if(header_line MATCHES "^PSLOG_API ")
            if(NOT documentation_ready)
                message(FATAL_ERROR
                    "public declaration lacks a clangd-visible Doxygen comment: "
                    "${public_header}:${line_number}: ${header_line}")
            endif()
            set(documentation_ready FALSE)
        elseif(NOT header_line MATCHES "^[ \\t]*$")
            set(documentation_ready FALSE)
        endif()
    endforeach()
endforeach()
