if(NOT DEFINED PSLOG_ROOT)
    message(FATAL_ERROR "PSLOG_ROOT is required")
endif()

foreach(public_header IN ITEMS include/pslog.h include/pslog_lua.h)
    set(header_path "${PSLOG_ROOT}/${public_header}")
    file(STRINGS "${header_path}" header_lines)
    set(documentation_ready FALSE)
    set(in_documentation FALSE)
    set(in_logger_struct FALSE)
    set(line_number 0)
    foreach(header_line IN LISTS header_lines)
        math(EXPR line_number "${line_number} + 1")
        if(header_line MATCHES "/\\*\\*")
            set(in_documentation TRUE)
        endif()
        if(in_documentation AND header_line MATCHES "\\*/")
            set(in_documentation FALSE)
            set(documentation_ready TRUE)
            continue()
        endif()
        if(header_line MATCHES "^struct pslog_logger \\{")
            set(in_logger_struct TRUE)
        elseif(in_logger_struct AND header_line MATCHES "^\\};")
            set(in_logger_struct FALSE)
        endif()
        set(is_public_declaration FALSE)
        if(header_line MATCHES "^PSLOG_API ")
            set(is_public_declaration TRUE)
        elseif(header_line MATCHES "^#define PSLOG_(TIME_FORMAT|DEFAULT_LINE_BUFFER_CAPACITY|LUA_INTEROP_ABI_VERSION)")
            set(is_public_declaration TRUE)
        elseif(header_line MATCHES "^[ \t]*PSLOG_(MODE|LEVEL|COLOR|NON_FINITE_FLOAT|FIELD)_[A-Z0-9_]+[ \t]*=")
            set(is_public_declaration TRUE)
        elseif(in_logger_struct AND
               header_line MATCHES "^[ \t]*(int|void|pslog_logger \\*)[ \t]*\\(\\*[A-Za-z0-9_]+\\)")
            set(is_public_declaration TRUE)
        endif()

        if(is_public_declaration)
            if(NOT documentation_ready)
                message(FATAL_ERROR
                    "public declaration lacks a clangd-visible Doxygen comment: "
                    "${public_header}:${line_number}: ${header_line}")
            endif()
            set(documentation_ready FALSE)
        elseif(NOT header_line MATCHES "^[ \\t]*$")
            set(documentation_ready FALSE)
        endif()
    endforeach()
endforeach()
