if(NOT DEFINED PSLOG_ROOT)
    message(FATAL_ERROR "PSLOG_ROOT is required")
endif()
if(NOT DEFINED PSLOG_VERSION_SOURCE_DIR)
    message(FATAL_ERROR "PSLOG_VERSION_SOURCE_DIR is required")
endif()
if(NOT DEFINED PSLOG_VERSION_PROBE_OUTPUT)
    message(FATAL_ERROR "PSLOG_VERSION_PROBE_OUTPUT is required")
endif()

include("${PSLOG_ROOT}/cmake/pslog_version.cmake")

file(WRITE "${PSLOG_VERSION_PROBE_OUTPUT}"
    "${PSLOG_RESOLVED_VERSION}|${PSLOG_PROJECT_VERSION_CORE}|${PSLOG_VERSION_MAJOR}|${PSLOG_VERSION_MINOR}|${PSLOG_VERSION_PATCH}\n")
