set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_SYSROOT "" CACHE PATH "" FORCE)

set(CMAKE_C_COMPILER /usr/bin/arm-linux-gnueabihf-gcc CACHE FILEPATH "")
set(CMAKE_AR /usr/bin/arm-linux-gnueabihf-ar CACHE FILEPATH "")
set(CMAKE_RANLIB /usr/bin/arm-linux-gnueabihf-ranlib CACHE FILEPATH "")
set(PSLOG_GNU_ROOT /usr/arm-linux-gnueabihf)

set(CMAKE_FIND_ROOT_PATH ${PSLOG_GNU_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CROSSCOMPILING_EMULATOR /usr/bin/qemu-arm;-L;${PSLOG_GNU_ROOT} CACHE STRING "")

set(PSLOG_TARGET_ARCH armhf CACHE STRING "" FORCE)
set(PSLOG_TARGET_OS linux CACHE STRING "" FORCE)
set(PSLOG_TARGET_LIBC gnu CACHE STRING "" FORCE)
