# Shared verified archive acquisition for external CMake dependencies.
function(pslog_resolve_dependency_cache)
    if(DEFINED CPKT_DEPENDENCY_CACHE AND NOT CPKT_DEPENDENCY_CACHE STREQUAL "")
        return()
    endif()
    if(DEFINED ENV{CPKT_DEPENDENCY_CACHE} AND NOT "$ENV{CPKT_DEPENDENCY_CACHE}" STREQUAL "")
        set(_pslog_dependency_cache_default "$ENV{CPKT_DEPENDENCY_CACHE}")
    elseif(DEFINED ENV{XDG_CACHE_HOME} AND NOT "$ENV{XDG_CACHE_HOME}" STREQUAL "")
        set(_pslog_dependency_cache_default "$ENV{XDG_CACHE_HOME}/c.pkt.systems/deps")
    elseif(DEFINED ENV{HOME} AND NOT "$ENV{HOME}" STREQUAL "")
        set(_pslog_dependency_cache_default "$ENV{HOME}/.cache/c.pkt.systems/deps")
    else()
        message(FATAL_ERROR "CPKT_DEPENDENCY_CACHE, XDG_CACHE_HOME, or HOME is required to acquire dependencies")
    endif()
    set(CPKT_DEPENDENCY_CACHE "${_pslog_dependency_cache_default}" CACHE PATH
        "Shared verified archive cache for external dependencies")
endfunction()

function(pslog_acquire_verified_archive)
    cmake_parse_arguments(ARG "" "COMPONENT;URL;SHA256;OUTPUT" "" ${ARGN})
    foreach(required COMPONENT URL SHA256 OUTPUT)
        if(NOT ARG_${required})
            message(FATAL_ERROR "pslog_acquire_verified_archive requires ${required}")
        endif()
    endforeach()
    pslog_resolve_dependency_cache()
    string(LENGTH "${ARG_SHA256}" sha256_length)
    if(NOT sha256_length EQUAL 64 OR NOT ARG_SHA256 MATCHES "^[0-9a-fA-F]+$")
        message(FATAL_ERROR "${ARG_COMPONENT}: SHA256 must be a 64-character hexadecimal digest")
    endif()
    if(NOT ARG_URL MATCHES "^https://" AND
       NOT (PSLOG_DEPENDENCY_TEST_ALLOW_FILE_URL AND ARG_URL MATCHES "^file://"))
        message(FATAL_ERROR "${ARG_COMPONENT}: dependency URL must use HTTPS")
    endif()

    get_filename_component(archive_name "${ARG_URL}" NAME)
    if(archive_name STREQUAL "")
        message(FATAL_ERROR "${ARG_COMPONENT}: dependency URL has no archive filename")
    endif()
    string(TOLOWER "${ARG_SHA256}" digest)
    set(cache_dir "${CPKT_DEPENDENCY_CACHE}/archives/sha256/${digest}")
    set(archive_path "${cache_dir}/${archive_name}")
    set(lock_path "${CPKT_DEPENDENCY_CACHE}/locks/${digest}.lock")
    file(MAKE_DIRECTORY "${cache_dir}" "${CPKT_DEPENDENCY_CACHE}/locks")
    file(LOCK "${lock_path}" GUARD FUNCTION TIMEOUT 120)

    set(cache_valid FALSE)
    if(EXISTS "${archive_path}")
        file(SHA256 "${archive_path}" actual_digest)
        if(actual_digest STREQUAL digest)
            set(cache_valid TRUE)
        else()
            file(REMOVE "${archive_path}")
        endif()
    endif()
    if(NOT cache_valid)
        string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
        set(temp_path "${cache_dir}/.${archive_name}.${nonce}.tmp")
        file(DOWNLOAD "${ARG_URL}" "${temp_path}"
            TLS_VERIFY ON EXPECTED_HASH "SHA256=${digest}"
            STATUS download_status LOG download_log)
        list(GET download_status 0 download_code)
        if(NOT download_code EQUAL 0 OR NOT EXISTS "${temp_path}")
            file(REMOVE "${temp_path}")
            list(GET download_status 1 download_reason)
            message(FATAL_ERROR
                "${ARG_COMPONENT}: verified dependency download failed\nurl=${ARG_URL}\n"
                "sha256=${digest}\ncache=${archive_path}\nreason=${download_reason}\n${download_log}")
        endif()
        file(SHA256 "${temp_path}" downloaded_digest)
        if(NOT downloaded_digest STREQUAL digest)
            file(REMOVE "${temp_path}")
            message(FATAL_ERROR "${ARG_COMPONENT}: downloaded archive checksum mismatch")
        endif()
        file(RENAME "${temp_path}" "${archive_path}")
    endif()
    set(${ARG_OUTPUT} "${archive_path}" PARENT_SCOPE)
endfunction()

function(pslog_stage_dependency_archive)
    cmake_parse_arguments(ARG "" "COMPONENT;ARCHIVE;SHA256;OUTPUT" "" ${ARGN})
    foreach(required COMPONENT ARCHIVE SHA256 OUTPUT)
        if(NOT ARG_${required})
            message(FATAL_ERROR "pslog_stage_dependency_archive requires ${required}")
        endif()
    endforeach()
    string(TOLOWER "${ARG_SHA256}" digest)
    set(stage_root "${CMAKE_SOURCE_DIR}/.cache/deps/${ARG_COMPONENT}-${digest}")
    set(stamp "${stage_root}/.pslog-archive-sha256")
    # The staged source directory is shared by all build presets.  Keep the
    # lock through validation and extraction so a concurrent configure cannot
    # remove a tree another configure has just started to consume.
    set(stage_lock_path "${CMAKE_SOURCE_DIR}/.cache/deps/locks/${ARG_COMPONENT}-${digest}.lock")
    file(MAKE_DIRECTORY "${CMAKE_SOURCE_DIR}/.cache/deps/locks")
    file(LOCK "${stage_lock_path}" GUARD FUNCTION TIMEOUT 120)
    if(NOT EXISTS "${stamp}" OR NOT EXISTS "${stage_root}/CMakeLists.txt")
        file(REMOVE_RECURSE "${stage_root}")
        file(MAKE_DIRECTORY "${stage_root}")
        file(ARCHIVE_EXTRACT INPUT "${ARG_ARCHIVE}" DESTINATION "${stage_root}")
        file(GLOB extracted_roots LIST_DIRECTORIES true "${stage_root}/*")
        list(LENGTH extracted_roots extracted_root_count)
        if(extracted_root_count EQUAL 1 AND IS_DIRECTORY "${extracted_roots}")
            file(GLOB extracted_files "${extracted_roots}/*")
            foreach(extracted_file IN LISTS extracted_files)
                get_filename_component(extracted_name "${extracted_file}" NAME)
                file(RENAME "${extracted_file}" "${stage_root}/${extracted_name}")
            endforeach()
            file(REMOVE_RECURSE "${extracted_roots}")
        endif()
        file(WRITE "${stamp}" "${digest}\n")
    endif()
    set(${ARG_OUTPUT} "${stage_root}" PARENT_SCOPE)
endfunction()
