include_guard(GLOBAL)

function(pslog_normalize_arch input output)
    string(TOLOWER "${input}" arch)
    if(arch MATCHES "^(amd64|x86_64)$")
        set(arch x86_64)
    elseif(arch MATCHES "^(arm64|aarch64)$")
        set(arch aarch64)
    elseif(arch MATCHES "^(armhf|armv7.*|arm)$")
        set(arch armhf)
    endif()
    set(${output} "${arch}" PARENT_SCOPE)
endfunction()

pslog_normalize_arch("${CMAKE_HOST_SYSTEM_PROCESSOR}" host_arch)
pslog_normalize_arch("${CMAKE_SYSTEM_PROCESSOR}" target_arch)
set(PSLOG_NATIVE_EXECUTION FALSE)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL CMAKE_SYSTEM_NAME AND host_arch STREQUAL target_arch)
    set(PSLOG_NATIVE_EXECUTION TRUE)
endif()

# This module belongs only to build-tree executables and verification projects.
# Do not install it or export its flags through SDK metadata.
function(pslog_local_runtime_flags output)
    set(${output} "" PARENT_SCOPE)
    if(PSLOG_ALLOW_HOST_COMPILER)
        return()
    endif()
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR NOT PSLOG_NATIVE_EXECUTION)
        return()
    endif()
    if(NOT IS_DIRECTORY "${PSLOG_BOOTLIN_SYSROOT}")
        message(FATAL_ERROR "Native Linux execution requires a selected Bootlin sysroot")
    endif()
    if(CMAKE_C_COMPILER_TARGET MATCHES "musl")
        set(loader_name "ld-musl-${target_arch}.so.1")
    elseif(target_arch STREQUAL "x86_64")
        set(loader_name ld-linux-x86-64.so.2)
    elseif(target_arch STREQUAL "aarch64")
        set(loader_name ld-linux-aarch64.so.1)
    elseif(target_arch STREQUAL "armhf")
        set(loader_name ld-linux-armhf.so.3)
    else()
        message(FATAL_ERROR "Unsupported native ELF architecture: ${target_arch}")
    endif()
    set(loader "${PSLOG_BOOTLIN_SYSROOT}/lib/${loader_name}")
    if(NOT EXISTS "${loader}")
        message(FATAL_ERROR "Selected Bootlin runtime is missing its interpreter: ${loader}")
    endif()
    file(REAL_PATH "${PSLOG_BOOTLIN_SYSROOT}" sysroot)
    file(REAL_PATH "${loader}" real_loader)
    string(FIND "${real_loader}" "${sysroot}/" contained)
    if(NOT contained EQUAL 0)
        message(FATAL_ERROR "Bootlin interpreter escapes the selected sysroot: ${loader}")
    endif()
    execute_process(COMMAND "${CMAKE_READELF}" -h "${loader}"
        RESULT_VARIABLE result OUTPUT_VARIABLE header ERROR_VARIABLE error)
    if(target_arch STREQUAL "x86_64")
        set(machine "Advanced Micro Devices X86-64")
    elseif(target_arch STREQUAL "aarch64")
        set(machine "AArch64")
    else()
        set(machine "ARM")
    endif()
    if(NOT result EQUAL 0 OR NOT header MATCHES "Machine:[ \t]+${machine}([\r\n]|$)")
        message(FATAL_ERROR "Bootlin interpreter architecture mismatch: ${loader}\n${header}${error}")
    endif()
    set(paths "$ORIGIN")
    foreach(dir lib usr/lib lib64 usr/lib64)
        if(IS_DIRECTORY "${sysroot}/${dir}")
            list(APPEND paths "${sysroot}/${dir}")
        endif()
    endforeach()
    # Query target runtime locations; the collection's top-level lib contains
    # host libraries used to run the compiler and must never enter this list.
    foreach(lib libgcc_s.so.1 libstdc++.so.6 libasan.so libubsan.so libatomic.so.1)
        execute_process(COMMAND "${CMAKE_C_COMPILER}" "-print-file-name=${lib}"
            OUTPUT_VARIABLE file OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
        if(result EQUAL 0 AND IS_ABSOLUTE "${file}" AND EXISTS "${file}")
            file(REAL_PATH "${file}" file)
            string(FIND "${file}" "${PSLOG_BOOTLIN_ROOT}/" contained)
            if(NOT contained EQUAL 0)
                message(FATAL_ERROR "Target runtime escapes Bootlin collection: ${file}")
            endif()
            get_filename_component(dir "${file}" DIRECTORY)
            list(APPEND paths "${dir}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES paths)
    list(JOIN paths ":" search)
    set(flags "-Wl,--dynamic-linker,${loader}" "-Wl,--disable-new-dtags,-rpath,${search}" "-Wl,--fatal-warnings")
    set(${output} "${flags}" PARENT_SCOPE)
    set(PSLOG_BOOTLIN_ELF_INTERPRETER "${loader}" CACHE FILEPATH "Private interpreter" FORCE)
    set(PSLOG_BOOTLIN_RUNTIME_SEARCH_PATH "${search}" CACHE STRING "Private runtime directories" FORCE)
    list(JOIN flags " " text)
    set(PSLOG_NONSHIPPED_ELF_LINKER_FLAGS "${text}" CACHE STRING "Private executable link options" FORCE)
endfunction()

pslog_local_runtime_flags(PSLOG_LOCAL_RUNTIME_FLAGS)

function(pslog_configure_nonshipped_executable target)
    target_link_options(${target} PRIVATE ${PSLOG_LOCAL_RUNTIME_FLAGS})
endfunction()
