# Inspect ELF magic rather than filenames, including extensionless executables.
function(pslog_assert_linux_runpath path)
    file(READ "${path}" magic LIMIT 4 HEX)
    if(NOT magic STREQUAL "7f454c46")
        return()
    endif()
    if(DEFINED PSLOG_READELF AND NOT PSLOG_READELF STREQUAL "")
        set(reader "${PSLOG_READELF}")
    else()
        find_program(reader NAMES readelf llvm-readelf REQUIRED)
    endif()
    execute_process(COMMAND "${reader}" -W -h -l -d -s "${path}"
        RESULT_VARIABLE result OUTPUT_VARIABLE metadata ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT metadata MATCHES "ELF Header:")
        message(FATAL_ERROR "Cannot inspect ELF release artifact: ${path}\n${error}")
    endif()
    if(metadata MATCHES "Requesting program interpreter: ([^]]+)")
        set(interpreter "${CMAKE_MATCH_1}")
        set(system_interpreters
            /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-aarch64.so.1
            /lib/ld-linux-armhf.so.3 /lib/ld-musl-x86_64.so.1
            /lib/ld-musl-aarch64.so.1 /lib/ld-musl-armhf.so.1)
        if(NOT interpreter IN_LIST system_interpreters)
            message(FATAL_ERROR "ELF artifact contains a non-system interpreter '${interpreter}': ${path}")
        endif()
    endif()
    string(REGEX MATCHALL "\\((RPATH|RUNPATH)\\)[^\n]*\\[[^]]*\\]" paths "${metadata}")
    foreach(line IN LISTS paths)
        string(REGEX REPLACE ".*\\[([^]]*)\\].*" "\\1" entries "${line}")
        if(entries STREQUAL "")
            message(FATAL_ERROR "ELF artifact contains non-relocatable RPATH/RUNPATH '': ${path}")
        endif()
        string(REPLACE ":" ";" entries "${entries}")
        foreach(entry IN LISTS entries)
            if(NOT entry MATCHES "^\\$ORIGIN(/[^:]+)?$")
                message(FATAL_ERROR "ELF artifact contains non-relocatable RPATH/RUNPATH '${entry}': ${path}")
            endif()
        endforeach()
    endforeach()
    string(REGEX MATCHALL "\\((NEEDED|SONAME)\\)[^\n]*\\[[^]]*\\]" names "${metadata}")
    foreach(line IN LISTS names)
        string(REGEX REPLACE ".*\\[([^]]*)\\].*" "\\1" name "${line}")
        if(name MATCHES "/")
            message(FATAL_ERROR "ELF artifact contains an absolute or relative dependency path '${name}': ${path}")
        endif()
        if(line MATCHES "SONAME" AND name MATCHES "^(ld-linux|ld-musl|ld64|libc\\.so)")
            message(FATAL_ERROR "Release artifact bundles a libc loader: ${path}")
        endif()
    endforeach()
    get_filename_component(name "${path}" NAME)
    # Symbols also catch renamed/stripped loaders (musl's loader is libc).
    if(name MATCHES "^(ld-linux|ld-musl|ld64)" OR
       metadata MATCHES "[ \t](_dl_start|_dl_open|__libc_start_main)(@@[^ \n]+)?[ \n]")
        # Undefined references to libc are normal; only definitions identify it.
        string(REGEX MATCH "[0-9]+:[^\n]*[ \t](GLOBAL|WEAK)[ \t]+DEFAULT[ \t]+[0-9]+[ \t]+(_dl_start|_dl_open|__libc_start_main)" definition "${metadata}")
        if((definition AND metadata MATCHES "Type:[ \t]+DYN") OR name MATCHES "^(ld-linux|ld-musl|ld64)")
            message(FATAL_ERROR "Release artifact bundles a libc loader: ${path}")
        endif()
    endif()
endfunction()
